### ISSUE TITLE
Wrong location of hotswap-agent.jar in MacOS build

### ISSUE THREAD

**Issue by theigl** [TravaOpenJDK/trava-jdk-11-dcevm#1]
Starting an application with the downloaded binaries results in:

    HotswapAgent not found on path:'/dcevm-11+0/Contents/Home/lib/hotswap/hotswap-agent.jar'

In the latest MacOS build `hotswap-agent.jar` ends up in `/lib/hotswap/hotswap-agent.jar`. The correct location would be `/Contents/Home/lib/hotswap/hotswap-agent.jar`.

**Comment by skybber** [comment]
Fixed, thanks for report :1st_place_medal:
