### ISSUE TITLE
Option to provide libjvm.so as a standalone release

### ISSUE THREAD

**Issue by sofiageo** [TravaOpenJDK/trava-jdk-11-dcevm#11]
Hi and sorry for my ignorance, is there a techical reason the libjvm.so is provided only inside the TravaOpenJDK? It sounds more simple to be able to copy the file to our existing JVM installations. If there isn't, do you think it would be possible to add it as an additional release? 

The README for https://github.com/dcevm/dcevm gives the impression that DCEVM binaries can be found in this repository, which is a bit confusing.

Thanks!

**Comment by skybber** [comment]
There is no technical reason, it is doable either inside the current trava11 project or as an extra project, which I prefer. Actually I don't have time to do that, so anyone who would like to contribute to this project is welcomed.

**Comment by sofiageo** [comment]
> There is no technical reason, it is doable either inside the current trava11 project or as an extra project, which I prefer. Actually I don't have time to do that, so anyone who would like to contribute to this project is welcomed.

Thanks, it's understandable. I'll try to take a look on the source code on how this file is created / provided and find out if I can contribute.

**Comment by skybber** [comment]
Currently trava jdk can be used as system jdk.
