### ISSUE TITLE
.travis.yml/build_windows.sh download openjdk10 instead of openjdk11

### ISSUE THREAD

**Issue by markiewb** [TravaOpenJDK/trava-jdk-11-dcevm#12]
See https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/search?q=openjdk10&unscoped_q=openjdk10

**Comment by skybber** [comment]
It should not be problem since it is boot jdk used for build actual jdk-11 or have you some problem with this?

**Comment by markiewb** [comment]
No issues so far. If it is only the boot JDK then fine. Thank you

I will close the issue.
