### ISSUE TITLE
HotSwapAgent: failed to convert filePath

### ISSUE THREAD

**Issue by tholu** [TravaOpenJDK/trava-jdk-11-dcevm#14]
I'm getting the following errors when using TravaJDK with my Maven project with the `jetty-maven-plugin`:

```
HOTSWAP AGENT: 15:35:47.415 ERROR (org.hotswap.agent.plugin.spring.scanner.XmlBeanDefinationScannerAgent) - failed to convert filePath /{project}/target/www/WEB-INF/app-security.xml to classPath path
HOTSWAP AGENT: 15:36:01.538 ERROR (org.hotswap.agent.plugin.spring.scanner.XmlBeanDefinationScannerAgent) - failed to convert filePath /{project}/target/www/WEB-INF/mvc-config.xml to classPath path
HOTSWAP AGENT: 15:36:01.745 ERROR (org.hotswap.agent.plugin.spring.scanner.XmlBeanDefinationScannerAgent) - failed to convert filePath /{project}/target/www/WEB-INF/app-servlet.xml to classPath path
```

I tried using a `hotswap-agent.properties` in `src/main/resources` to configure the Hotswap Agent, but it does not seem to be picked up. Any ideas how to fix/debug this?

**Comment by skybber** [comment]
It's is HoatswapAgent issue, please create one there.

**Comment by tholu** [comment]
Is it? Maybe it's a configuration issue, any advice how to configure the HotswapAgent with TravaJDK? Or don't you do that at all?

**Comment by skybber** [comment]
Look at HA issues, there is some similar one.
