### ISSUE TITLE
build for jdk 12, jdk 13

### ISSUE THREAD

**Issue by noguespi** [TravaOpenJDK/trava-jdk-11-dcevm#16]
Is there existing build for jdk 12 / jdk 13 ? 
Is it complicated to make a build of dcevm targeting these versions ?

**Comment by skybber** [comment]
There is no such build yet. It used to be not so trivial to make upgrade, because you have to apply dcevm patches on top of openjdkjdk12/13 sources and resolve conflict, modify jdk C++ code... Upgrade from java8 to java11 was pretty hard.

**Comment by noguespi** [comment]
I see, thank you.

**Comment by Shadowrs** [comment]
For future reference for anyone that is looking for java 12/13/14/15+ the devs said they may support Long Term Releases (not 6 month-releases) but its still a lot of work. I guess dcevm is jdk11 for forseable future. Probs worth adding this to the various repo's READMEs

https://groups.google.com/g/hotswapagent/c/MU85QPkUY04/m/J0nlanRWCQAJ
