### ISSUE TITLE
New Release with HotswapAgent 1.4.0

### ISSUE THREAD

**Issue by tholu** [TravaOpenJDK/trava-jdk-11-dcevm#22]
There has been a new release of HotswapAgent: https://github.com/HotswapProjects/HotswapAgent/releases/tag/RELEASE-1.4.0

Can you release an updated version of TravaOpenJDK including the new HotswapAgent as well? Thanks!

**Comment by skybber** [comment]
Thanks for report, I've already looked on the problem, it is since hibernate 6.0 when they changed class to interface. I''ll try to create new version this weekend.

**Comment by tholu** [comment]
I guess your answer is referencing this issue? https://github.com/HotswapProjects/HotswapAgent/issues/331 

Thanks a lot!

**Comment by skybber** [comment]
Done

**Comment by tholu** [comment]
Thanks for the superfast release! 

Dcevm-11.0.5+5 (**2019**-01-26)

Small typo in release title 😉

**Comment by ghuser** [comment]
Is there any fix or workaround related to [HotswapProjects/HotswapAgent#331](https://github.com/HotswapProjects/HotswapAgent/issues/331) referenced above?

Because we are facing this issue too.

**Comment by skybber** [comment]
With Dcevm-11.0.9+2 ?

**Comment by skybber** [comment]
I've looked into commits, there should be fix for it in 1.4.2-SNAPSHOT

https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.4.2-SNAPSHOT

You can replace `hotswap-agent.jar` with `1.4.2-SNAPSHOT` in `lib/hotswap` of Trava distribution, use the old name `hotswap-agent.jar` for it.
