### ISSUE TITLE
javaw.exe dies with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by alexander017** [TravaOpenJDK/trava-jdk-11-dcevm#25]
Hi, 

first of all thank you for this great alternative for the much to expensive JRebel!

Unfortunately I'm facing a problem that I can't resolve on my own. When starting my application from inside Eclipse in debug mode the java.exe process is terminating after a few seconds saying:
```
 _A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8a084dfd5, pid=97792, tid=72004

 JRE version: OpenJDK Runtime Environment (11.0.7+2) (build 11.0.7+2-202006131924)
 Java VM: Dynamic Code Evolution 64-Bit Server VM (11.0.7+2-202006131924, mixed mode, tiered, compressed oops, serial gc, windows-amd64)
 Problematic frame:
 V  [jvm.dll+0x60dfd5]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-build/issues


---------------  S U M M A R Y ------------

Command Line: -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:61860 -DCONF=D:/usr/abcd/coretrunkvm_oracle/etc -DENABLE_EXT_LOADER=true -Dsecurity.enabled=false -DDEV_MODE=true -javaagent:D:\Programme\eclipse-jee-2020-03-R-incubation-win32-x86_64\configuration\org.eclipse.osgi\411\0\.cp\lib\javaagent-shaded.jar -Dfile.encoding=UTF-8 com.abcd.corex.apps.compat.CompatAppSampleApplication --server.servlet.context-path=/abcd --logging.config=D:/usr/abcd/coretrunkvm_oracle/etc/log4j2_abcd.xml

Host: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 8 cores, 31G,  Windows 10 , 64 bit Build 17134 (10.0.17134.1425)
Time: Fri Jul 24 17:44:33 2020 Mitteleuropäische Sommerzeit elapsed time: 4 seconds (0d 0h 0m 4s)

---------------  T H R E A D  ---------------

Current thread (0x0000020520481800):  WatcherThread [stack: 0x000000eb6ee00000,0x000000eb6ef00000] [id=72004]

Stack: [0x000000eb6ee00000,0x000000eb6ef00000],  sp=0x000000eb6eeffb10,  free space=1022k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x60dfd5]
V  [jvm.dll+0x673c8f]
V  [jvm.dll+0x6bec7d]
V  [jvm.dll+0x6e47f9]
V  [jvm.dll+0x6dd8e4]
V  [jvm.dll+0x5e5d16]
C  [ucrtbase.dll+0x1e3fe]
C  [KERNEL32.DLL+0x14034]
C  [ntdll.dll+0x73691]


siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000c0000000b


Register to memory mapping:

RIP=0x00007ff8a084dfd5 jvm.dll
RAX=0x0000000c0000000b is an unknown value
RBX=0x0000020520123570 points into unknown readable memory: e0 1b ab a0 f8 7f 00 00
RCX=0x000002051e5fbf80 points into unknown readable memory: 0b 00 00 00 0c 00 00 00
RDX=0x0000000000000032 is an unknown value
RSP=0x000000eb6eeffb10 points into unknown readable memory: a0 1e a6 02 05 02 00 00_
```
I tried this with 11.0.5+5, 11.0.6+1 and 11.0.7 from +2 to +4. It was always the same.

Standard AdoptOpenJDK, e.g. 11.0.8+10, is running well. 

It would be very nice it you can take at this or give me an hint.

Thx.
Alex

**Comment by skybber** [comment]
Does it fail after code modification? Is it failing with `-XX:-AllowEnhancedClassRedefinition` ?

**Comment by alexander017** [comment]
I tried 11.0.7+4 with -XX:-AllowEnhancedClassRedefinition and it is also failing.

**Comment by skybber** [comment]
Without code change?

**Comment by alexander017** [comment]
Yes, it fails just some seconds after application start without code change. In the Eclipse debugging perspective I see the main thread for about 2 seconds and than the process terminates.

**Comment by skybber** [comment]
It looks strange since there are no significant changes in dcevm in comparison to openjdk. Windows build does not have debug information unfortunately, co there si no clue in your stack trace. Do you have this problem on another projects? Does it fail even without HotswapAgent?

**Comment by alexander017** [comment]
I made some more tests and it seems like it is an impact from using it with eclipse. 
I downloaded AdoptOpenJDK 11.0.7+4 and it also crashes when run by eclipse. 11.0.8+10 is working well.
I'm using eclipse-jee-2020-03-R-incubation-win32-x86_64 and start it with AdoptOpenJDK 11.0.8+10.

When I start my application from cmd everything is working well even with dcevm-11.0.7+4. 

So I think this is not an HotswapAgent issue and the question is if you could provide a new version based on 11.0.8+10 or some version close to it.

Anyway, thanks for the help.
