### ISSUE TITLE
Document how to set options for integrated agent

### ISSUE THREAD

**Issue by cdalexndr** [TravaOpenJDK/trava-jdk-11-dcevm#28]
From original hotswap agent documentation:
`-javaagent:[yourpath/]hotswap-agent.jar=[option1]=[value1],[option2]=[value2]`

How to use these options when the agent is automatically loaded?

**Comment by skybber** [comment]
Intention is to have hotswapagent-core  in JDK and use selected plugin using maven on application side. No need to have fatjar.

https://mvnrepository.com/artifact/org.hotswapagent

**Comment by cdalexndr** [comment]
I'm using binaries (1.4.1), according to Install documentation and it already contains plugins:
` Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]`

I haven't added any plugin from maven.

**Comment by skybber** [comment]
Sorry for delay, it is not possible to pass the options to built-in hotswapagent in commandline, but you can use hotswap-agent.properties and put it into your application resources. We didn't consider the passing options as command line argument yet...

**Comment by cdalexndr** [comment]
Note that this info is missing from github repo main page, but is present on: http://hotswapagent.org/mydoc_quickstart-jdk11.html

**Comment by skybber** [comment]
There already is something:
`(optional) create a file named "hotswap-agent.properties" inside your resources directory, see available properties and default values: https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/resources/hotswap-agent.properties`

**Comment by cdalexndr** [comment]
Not on this page: https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/blob/master/README.md

**Comment by skybber** [comment]
Ok, there should be some link to extended HA configuration.

**Comment by skybber** [comment]
There is a new JVM option -XX:HotswapAgent=[disabled,fatjar,core,external] in [dcevm11.0.9](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.9%2B1)
