### ISSUE TITLE
HotswapAgent not found when using -XX:HotswapAgent=core

### ISSUE THREAD

**Issue by roggenbrot** [TravaOpenJDK/trava-jdk-11-dcevm#33]
When using the new option `-XX:HotswapAgent=core` on `dcevm-11.0.9` the following message is printed on startup, and hotswap is disabled:

```
HotswapAgent not found on path:'/home/app/java/lib/hotswap/hotswap-agent-core.jar'!
```

Seems that there is no such jar available, either on linux or windows:

```
xxxxxxxxxxxxxxxxxxx:/home/app/java/lib/hotswap# ls
hotswap-agent.jar

```

Starting with option `-XX:HotswapAgent=fatjar` works without problems

(By the way, thanks for your effort to maintain these builds)

**Comment by skybber** [comment]
Thanks for feedback, probably there is bug in deployment skipping it. I'll fix in in next bugfix release. As a workaround you can copy core jar manually from https://github.com/HotswapProjects/HotswapAgent/releases/tag/RELEASE-1.4.1

**Comment by skybber** [comment]
Fixed in  https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.9%2B2
