### ISSUE TITLE
Config check

### ISSUE THREAD

**Issue by kdejaeger** [TravaOpenJDK/trava-jdk-11-dcevm#37]
For a spring boot app in intellij, is this the way to go with the latest versions? Because a lot of times after a CTRL-9 (compile project), I just have to reboot the project because of the errors.

![image](https://user-images.githubusercontent.com/279268/107539736-8e983080-6bc5-11eb-9ea3-86862090e8c3.png)

**Comment by skybber** [comment]
-XX:HotswapAgent=fatjar should be sufficient

**Comment by kdejaeger** [comment]
It's this issue: https://github.com/HotswapProjects/HotswapAgent/issues/383
I disabled the Hibernate plugin for now through, hot-swap.properties.
