### ISSUE TITLE
Availability of linux aarch64/arm64 build

### ISSUE THREAD

**Issue by markdbuck** [TravaOpenJDK/trava-jdk-11-dcevm#39]
@skybber I have been able to successfully build decvm on linux/aarch64 using Travis-CI. Would you be interested in an update to your .travis.yml file that builds linux for both amd64 and aarch64? If so, I will clean up what I did and let you know when complete.

**Comment by skybber** [comment]
Great! Yes, please.

**Comment by markdbuck** [comment]
@skybber I submitted a pull request for your consideration.

**Comment by skybber** [comment]
@markdbuck Last build looks good, thanks for contribution.
