### ISSUE TITLE
Error when use "jar" in command line

### ISSUE THREAD

**Issue by ming871** [TravaOpenJDK/trava-jdk-11-dcevm#4]
Starting HotswapAgent '/Library/Java/JavaVirtualMachines/dcevm-11.0.1.6/Contents/Home/lib/hotswap/hotswap-agent.jar'
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message find class on InstrumentationImpl failed at  line: 493
*** java.lang.instrument ASSERTION FAILED ***: "result" at  line: 402
FATAL ERROR in native method: processing of -javaagent failed

**Comment by skybber** [comment]
Does the `/Library/Java/JavaVirtualMachines/dcevm-11.0.1.6/Contents/Home/lib/hotswap/hotswap-agent.jar` exist?

**Comment by ming871** [comment]
Yes

devdeiMac-Pro:bin dev$ ls -la /Library/Java/JavaVirtualMachines/dcevm-11.0.1.6/Contents/Home/lib/hotswap/hotswap-agent.jar
-rw-r--r--@ 1 dev  staff  1591365 12  7 00:45 /Library/Java/JavaVirtualMachines/dcevm-11.0.1.6/Contents/Home/lib/hotswap/hotswap-agent.jar

**Comment by skybber** [comment]
I've tested `java -jar xyz.jar` and it is working for me on linux. So it is failing on OSX? What about removing `hotswap-agent.jar` from `lib/hotswap` ?

**Comment by ming871** [comment]
sorry, my mistake. 
I mean the "jar" command to create ".jar" archive file, like "jar cvf file.jar -C fatjar/ .", 
not "java -jar" to run a java app from/in one jar file.

**Comment by skybber** [comment]
OK, you are using jdk11-dcevm as a system JDK? I do not recommend it, since it has limitations like default Serial GC (despite you can use CMS). It is intended as an alternative JDK for debugging and development. However I will try to check and fix the problem ...

**Comment by skybber** [comment]
Its not recommended, but if you can, you can try it with -XX:+UseConcMarkSweepGC - it should work quite OK, but not fully tested yet.

**Comment by ming871** [comment]
Ok, Thank you! I will try it.
