### ISSUE TITLE
Missing release artifacts for Linux in dcevm-11.0.15+1?

### ISSUE THREAD

**Issue by ilgrosso** [TravaOpenJDK/trava-jdk-11-dcevm#56]
Only Windows and MacOS as it seems: https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.15%2B1

**Comment by skybber** [comment]
I had to move the project to GithubActions because Travis changed the policy for the open source projects, I§m little bit fighting with it, but could be prepared this evening.

**Comment by ilgrosso** [comment]
Thank you for prompt reaction.
I totally understand the issues of moving away from Travis CI!

**Comment by skybber** [comment]
Done, there are some new fixes, but pretty old HA, if you need new one use newest [1.4.2-SNAPSHOT](https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.4.2-SNAPSHOT) , there are some CDI fixes...

**Comment by ilgrosso** [comment]
Thank you @skybber
