### ISSUE TITLE
Support for G1GC

### ISSUE THREAD

**Issue by lambcode** [TravaOpenJDK/trava-jdk-11-dcevm#8]
Are there any plans for supporting [G1GC](https://www.oracle.com/technetwork/java/javase/tech/g1-intro-jsp-135488.html)?

**Comment by skybber** [comment]
G1 patch is much more difficult then CMS, it is too different from serial/cms gcs. I don't have any plan to do it, but it could be nice problem for diploma thesis for anyone. Anyway ZGC patch could be much easier, since the internal structure is similar to SerialGC.

**Comment by skybber** [comment]
G1 is supported now.
